#pragma checksum "..\..\control.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7A4237EB306EF70A75E2AF7A97FB07A9A511FBDD438B3ADE807BBBB3C6A2D5D2"
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Robot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Robot {
    
    
    /// <summary>
    /// control
    /// </summary>
    public partial class control : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 199 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT1;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT2;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT3;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT4;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse Point1;
        
        #line default
        #line hidden
        
        
        #line 222 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label postest;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_11;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_21;
        
        #line default
        #line hidden
        
        
        #line 238 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_31;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_41;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_51;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_61;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_71;
        
        #line default
        #line hidden
        
        
        #line 243 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_81;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_91;
        
        #line default
        #line hidden
        
        
        #line 245 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_110;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_32;
        
        #line default
        #line hidden
        
        
        #line 248 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_42;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_52;
        
        #line default
        #line hidden
        
        
        #line 250 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_62;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_72;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_82;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_92;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_120;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse Point2;
        
        #line default
        #line hidden
        
        
        #line 265 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT1_2;
        
        #line default
        #line hidden
        
        
        #line 266 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT2_2;
        
        #line default
        #line hidden
        
        
        #line 267 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT3_2;
        
        #line default
        #line hidden
        
        
        #line 268 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line AT4_2;
        
        #line default
        #line hidden
        
        
        #line 269 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_12;
        
        #line default
        #line hidden
        
        
        #line 275 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_22;
        
        #line default
        #line hidden
        
        
        #line 281 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_322;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_422;
        
        #line default
        #line hidden
        
        
        #line 283 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_522;
        
        #line default
        #line hidden
        
        
        #line 284 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_622;
        
        #line default
        #line hidden
        
        
        #line 285 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_722;
        
        #line default
        #line hidden
        
        
        #line 286 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_822;
        
        #line default
        #line hidden
        
        
        #line 287 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_922;
        
        #line default
        #line hidden
        
        
        #line 288 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_122;
        
        #line default
        #line hidden
        
        
        #line 290 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_312;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_412;
        
        #line default
        #line hidden
        
        
        #line 292 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_512;
        
        #line default
        #line hidden
        
        
        #line 293 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_612;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_712;
        
        #line default
        #line hidden
        
        
        #line 295 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_812;
        
        #line default
        #line hidden
        
        
        #line 296 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_912;
        
        #line default
        #line hidden
        
        
        #line 297 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line line_112;
        
        #line default
        #line hidden
        
        
        #line 328 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button connect;
        
        #line default
        #line hidden
        
        
        #line 331 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button disconnect;
        
        #line default
        #line hidden
        
        
        #line 334 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox com;
        
        #line default
        #line hidden
        
        
        #line 371 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label x_get;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label y_get;
        
        #line default
        #line hidden
        
        
        #line 461 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox x_set;
        
        #line default
        #line hidden
        
        
        #line 468 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox y_set;
        
        #line default
        #line hidden
        
        
        #line 474 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox z_set;
        
        #line default
        #line hidden
        
        
        #line 482 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox A4_set;
        
        #line default
        #line hidden
        
        
        #line 493 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button send_data;
        
        #line default
        #line hidden
        
        
        #line 498 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pick;
        
        #line default
        #line hidden
        
        
        #line 501 "..\..\control.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button place;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Robot;component/control.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\control.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.AT1 = ((System.Windows.Shapes.Line)(target));
            return;
            case 2:
            this.AT2 = ((System.Windows.Shapes.Line)(target));
            return;
            case 3:
            this.AT3 = ((System.Windows.Shapes.Line)(target));
            return;
            case 4:
            this.AT4 = ((System.Windows.Shapes.Line)(target));
            return;
            case 5:
            this.Point1 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 6:
            this.postest = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.line_11 = ((System.Windows.Shapes.Line)(target));
            return;
            case 8:
            this.line_21 = ((System.Windows.Shapes.Line)(target));
            return;
            case 9:
            this.line_31 = ((System.Windows.Shapes.Line)(target));
            return;
            case 10:
            this.line_41 = ((System.Windows.Shapes.Line)(target));
            return;
            case 11:
            this.line_51 = ((System.Windows.Shapes.Line)(target));
            return;
            case 12:
            this.line_61 = ((System.Windows.Shapes.Line)(target));
            return;
            case 13:
            this.line_71 = ((System.Windows.Shapes.Line)(target));
            return;
            case 14:
            this.line_81 = ((System.Windows.Shapes.Line)(target));
            return;
            case 15:
            this.line_91 = ((System.Windows.Shapes.Line)(target));
            return;
            case 16:
            this.line_110 = ((System.Windows.Shapes.Line)(target));
            return;
            case 17:
            this.line_32 = ((System.Windows.Shapes.Line)(target));
            return;
            case 18:
            this.line_42 = ((System.Windows.Shapes.Line)(target));
            return;
            case 19:
            this.line_52 = ((System.Windows.Shapes.Line)(target));
            return;
            case 20:
            this.line_62 = ((System.Windows.Shapes.Line)(target));
            return;
            case 21:
            this.line_72 = ((System.Windows.Shapes.Line)(target));
            return;
            case 22:
            this.line_82 = ((System.Windows.Shapes.Line)(target));
            return;
            case 23:
            this.line_92 = ((System.Windows.Shapes.Line)(target));
            return;
            case 24:
            this.line_120 = ((System.Windows.Shapes.Line)(target));
            return;
            case 25:
            this.Point2 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 26:
            this.AT1_2 = ((System.Windows.Shapes.Line)(target));
            return;
            case 27:
            this.AT2_2 = ((System.Windows.Shapes.Line)(target));
            return;
            case 28:
            this.AT3_2 = ((System.Windows.Shapes.Line)(target));
            return;
            case 29:
            this.AT4_2 = ((System.Windows.Shapes.Line)(target));
            return;
            case 30:
            this.line_12 = ((System.Windows.Shapes.Line)(target));
            return;
            case 31:
            this.line_22 = ((System.Windows.Shapes.Line)(target));
            return;
            case 32:
            this.line_322 = ((System.Windows.Shapes.Line)(target));
            return;
            case 33:
            this.line_422 = ((System.Windows.Shapes.Line)(target));
            return;
            case 34:
            this.line_522 = ((System.Windows.Shapes.Line)(target));
            return;
            case 35:
            this.line_622 = ((System.Windows.Shapes.Line)(target));
            return;
            case 36:
            this.line_722 = ((System.Windows.Shapes.Line)(target));
            return;
            case 37:
            this.line_822 = ((System.Windows.Shapes.Line)(target));
            return;
            case 38:
            this.line_922 = ((System.Windows.Shapes.Line)(target));
            return;
            case 39:
            this.line_122 = ((System.Windows.Shapes.Line)(target));
            return;
            case 40:
            this.line_312 = ((System.Windows.Shapes.Line)(target));
            return;
            case 41:
            this.line_412 = ((System.Windows.Shapes.Line)(target));
            return;
            case 42:
            this.line_512 = ((System.Windows.Shapes.Line)(target));
            return;
            case 43:
            this.line_612 = ((System.Windows.Shapes.Line)(target));
            return;
            case 44:
            this.line_712 = ((System.Windows.Shapes.Line)(target));
            return;
            case 45:
            this.line_812 = ((System.Windows.Shapes.Line)(target));
            return;
            case 46:
            this.line_912 = ((System.Windows.Shapes.Line)(target));
            return;
            case 47:
            this.line_112 = ((System.Windows.Shapes.Line)(target));
            return;
            case 48:
            this.connect = ((System.Windows.Controls.Button)(target));
            
            #line 329 "..\..\control.xaml"
            this.connect.Click += new System.Windows.RoutedEventHandler(this.connect_Click);
            
            #line default
            #line hidden
            
            #line 329 "..\..\control.xaml"
            this.connect.MouseEnter += new System.Windows.Input.MouseEventHandler(this.connect_MouseEnter);
            
            #line default
            #line hidden
            return;
            case 49:
            this.disconnect = ((System.Windows.Controls.Button)(target));
            
            #line 332 "..\..\control.xaml"
            this.disconnect.Click += new System.Windows.RoutedEventHandler(this.disconnect_Click);
            
            #line default
            #line hidden
            return;
            case 50:
            this.com = ((System.Windows.Controls.ComboBox)(target));
            
            #line 335 "..\..\control.xaml"
            this.com.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.com_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 51:
            this.x_get = ((System.Windows.Controls.Label)(target));
            return;
            case 52:
            this.y_get = ((System.Windows.Controls.Label)(target));
            return;
            case 53:
            this.x_set = ((System.Windows.Controls.TextBox)(target));
            return;
            case 54:
            this.y_set = ((System.Windows.Controls.TextBox)(target));
            return;
            case 55:
            this.z_set = ((System.Windows.Controls.TextBox)(target));
            return;
            case 56:
            this.A4_set = ((System.Windows.Controls.TextBox)(target));
            return;
            case 57:
            this.send_data = ((System.Windows.Controls.Button)(target));
            
            #line 497 "..\..\control.xaml"
            this.send_data.Click += new System.Windows.RoutedEventHandler(this.send_data_Click);
            
            #line default
            #line hidden
            return;
            case 58:
            this.pick = ((System.Windows.Controls.Button)(target));
            
            #line 500 "..\..\control.xaml"
            this.pick.Click += new System.Windows.RoutedEventHandler(this.pick_Click);
            
            #line default
            #line hidden
            return;
            case 59:
            this.place = ((System.Windows.Controls.Button)(target));
            
            #line 502 "..\..\control.xaml"
            this.place.Click += new System.Windows.RoutedEventHandler(this.place_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

